#!/bin/sh
#
# PROVIDE: movienight
# REQUIRE: networking
# KEYWORD: 
 
. /etc/rc.subr
 
name="movienight"
rcvar="${name}_enable"
command="/usr/local/${name}/MovieNight -f /usr/local/${name}/settings.json"
daemon_user="movien"
managerPid="/var/run/${name}.manager.pid"
mnPid="/var/run/${name}.pid"

start_cmd="daemon_start"
stop_cmd="daemon_stop"
status_cmd="daemon_status"

daemon_start() {
	/usr/sbin/daemon -P ${managerPid} -p ${mnPid} -r -f -S -o /var/log/${name}.log -u ${daemon_user} ${command}
}

daemon_stop() {
	if [ -e "${managerPid}" ]; 
	then
		kill -s TERM `cat ${managerPid}`
	else
		echo "${name} is not running"
	fi
}

daemon_status() {
	if [ -e "${mnPid}" ]; 
	then
		echo "${name} is running as pid `cat ${mnPid}`, with daemon manager (pid `cat ${managerPid}`)"
	else
		echo "${name} is not running"
	fi
}
 
load_rc_config $name
: ${rcvar:=no}
 
run_rc_command "$1"
