#!/bin/sh
#
# PROVIDE: movienight
# REQUIRE: networking
# KEYWORD: 
 
. /etc/rc.subr
 
name="movienight"
rcvar="${name}_enable"
command="/usr/local/${name}/MovieNight -f /usr/local/${name}/settings.json"
daemon_user="${name}"
pidfile="/var/run/${name}.pid"
 
start_cmd="daemon_start"
stop_cmd="daemon_stop"
status_cmd="daemon_status"

daemon_start() {
	/usr/sbin/daemon -P ${pidfile} -r -f -u $daemon_user $command
}

daemon_stop() {
	if [ -e "${pidfile}" ]; 
	then
		kill -s TERM `cat ${pidfile}`
	else
		echo "${name} is not running"
	fi
}

daemon_status() {
	if [ -e "${pidfile}" ]; 
	then
		echo "${name} is running as pid `cat ${pidfile}`"
	else
		echo "${name} is not running"
	fi
}
 
load_rc_config $name
: ${${name}_enable:=no}
 
run_rc_command "$1"
